zuul:
  sensitive-headers: 
  routes:
    # /productSer/product/list == /product(Eureka service name)/product/list
    productService:
      path: /productSer/**
      serviceId: PRODUCT
      # cookie and Dynamic routing
      sensitiveHeaders:
    # sample write
    #product: /productSer/**
  ignored-patterns:
    - /product/product/list
spring:
  redis:
    host: 47.94.128.132
    port: 6379
env: dev
