spring:
  application:
    name: order
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://m.limit-tech.com:3306/wxOrder?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: txhl1107mysql
# 配置获取Product Server规则
Product:
  ribbon:
    NFLoadBalancerR uleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
env: prod
file: 
  codeFormat: "UTF-8"
  localPath: "/usr/local/sunlin"
