spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://m.limit-tech.com:3306/wxOrder?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: txhl1107mysql
  rabbitmq:
    host: 47.94.128.132
    port: 5672
    username: guest
    password: guest
env: dev
file: 
  codeFormat: "UTF-8"
  localPath: "/usr/local/sunlin"
