spring:
  application:
    name: order
  datasource: 
    url: jdbc:mysql://m.limit-tech.com:3306/wxOrder?useUnicode=true&characterEncoding=UTF-8 
    driver-class-name: com.mysql.jdbc.Driver 
    username: root 
    password: txhl1107mysql 
eureka:
  client:
    service-url:
      defaultZone: http://47.94.128.132:8761/eureka/
env: 
  dev
