spring:
  application:
     name: product
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     username: wxOrder
     password: 123456
     url: jdbc:mysql://mysql:3306/wxOrder?useUnicode=true&characterEncoding=UTF-8
  rabbitmq:
    host: rabbit_service
    port: 5672
    username: admin
    password: admin
  redis:
    host: redis
    port: 6379
  jpa:
     show-sql: true
  zipkin:
    base-url: http://zipkin:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
logging:
  level:
    org.springframework.cloud.openfeign: debug
server:
  port: 8082
