spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.94.128.132:3306/wxOrder?useUnicode=true&characterEncoding=UTF-8
    username: wxOrder
    password: 123456
  redis:
    host: 47.94.128.132
    port: 6379
env: dev
